(() => {
  'use strict';
  const $ = (selector) => document.querySelector(selector);
  const state = { name: '', room: '', messages: [], stream: null, recorder: null, chunks: [] };
  const key = (room) => `mouja-room-${room}`;
  const alphabet = 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
  const icons = {
    wave: '<svg class="svg-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="M4 12c2.2-5.3 5.2-5.3 8 0s5.8 5.3 8 0"/><path d="M4 17c2.2-5.3 5.2-5.3 8 0s5.8 5.3 8 0"/></svg>',
    paperclip: '<svg class="svg-icon" viewBox="0 0 24 24" aria-hidden="true"><path d="m20 11-8.5 8.5a5 5 0 0 1-7-7L13 4a3.5 3.5 0 0 1 5 5l-8.5 8.5a2 2 0 1 1-3-3L14 7"/></svg>'
  };
  const icon = (name) => icons[name] || '';


  function makeCode() { let code = ''; for (let i = 0; i < 6; i += 1) code += alphabet[Math.floor(Math.random() * alphabet.length)]; return code; }
  function escapeHtml(value) { return String(value ?? '').replace(/[&<>'"]/g, (c) => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c])); }
  function formatBytes(bytes) { if (!bytes) return 'ملف'; const units = ['بايت','ك.ب','م.ب']; let i = 0; let n = bytes; while (n >= 1024 && i < 2) { n /= 1024; i += 1; } return `${n.toFixed(i ? 1 : 0)} ${units[i]}`; }
  function toast(text, kind = 'ok') { const item = document.createElement('div'); item.className = `toast ${kind}`; item.textContent = text; $('#toast-region').appendChild(item); setTimeout(() => item.remove(), 3600); }
  function openModal() { $('#entry-modal').classList.remove('hidden'); $('#nickname').focus(); }
  function closeModal() { $('#entry-modal').classList.add('hidden'); }
  function saveRoom() { localStorage.setItem(key(state.room), JSON.stringify({ name: state.name, messages: state.messages.slice(-80) })); }
  function loadRoom() { try { const data = JSON.parse(localStorage.getItem(key(state.room)) || '{}'); state.messages = Array.isArray(data.messages) ? data.messages : []; } catch { state.messages = []; } }
  function showRoom() { $('#landing-view').classList.add('hidden'); document.querySelector('.site-footer').classList.add('hidden'); $('#room-view').classList.remove('hidden'); $('#room-code-label').textContent = state.room; $('#room-code-big').textContent = state.room; $('#person-name').textContent = state.name || 'أنت'; $('#person-avatar').textContent = (state.name || 'أ').slice(0, 1); renderMessages(); }
  function showLanding() { stopMedia(); $('#room-view').classList.add('hidden'); $('#landing-view').classList.remove('hidden'); document.querySelector('.site-footer').classList.remove('hidden'); history.replaceState({}, '', './'); }
  function enterRoom(join = false) { const name = $('#nickname').value.trim() || 'ضيف'; const code = $('#join-code').value.trim().toUpperCase(); if (name.length < 2) { toast('اكتب اسماً قصيراً ليظهر في المساحة.', 'warn'); return; } if (join && code.length !== 6) { toast('أدخل رمزاً من 6 أحرف.', 'warn'); return; } state.name = name; state.room = join ? code : makeCode(); loadRoom(); closeModal(); showRoom(); history.replaceState({}, '', `./?room=${encodeURIComponent(state.room)}`); toast(join ? 'تم فتح المساحة محلياً.' : 'تم إنشاء مساحة جديدة على جهازك.', 'ok'); }
  function renderMessages() { const list = $('#messages'); list.innerHTML = ''; if (!state.messages.length) { list.innerHTML = `<div class="welcome-message"><span>${icon('wave')}</span><h2>أهلاً بك في مساحتك</h2><p>اكتب فكرة، ارفع ملفاً، أو افتح معاينة الوسائط. هذه المساحة خاصة بهذا الجهاز.</p></div>`; return; } state.messages.forEach(renderMessage); list.scrollTop = list.scrollHeight; }
  function renderMessage(message) { const list = $('#messages'); const item = document.createElement('article'); item.className = `message ${message.mine ? 'mine' : ''}`; const time = new Intl.DateTimeFormat('ar', { hour:'2-digit', minute:'2-digit' }).format(new Date(message.time)); let content = message.kind === 'file' ? `<div class="file-message">${icon('paperclip')}<div>${escapeHtml(message.name)}<span>${formatBytes(message.size)}</span></div></div>` : `<p>${escapeHtml(message.text)}</p>`; item.innerHTML = `<div class="message-meta"><strong>${escapeHtml(message.mine ? 'أنت' : message.name)}</strong><time>${time}</time></div>${content}`; list.appendChild(item); }
  function sendText(event) { event.preventDefault(); const input = $('#message-input'); const text = input.value.trim(); if (!text) return; state.messages.push({ kind:'text', text:text.slice(0, 4000), name:state.name, mine:true, time:Date.now() }); saveRoom(); if ($('#messages .welcome-message')) $('#messages').innerHTML = ''; renderMessage(state.messages[state.messages.length - 1]); input.value = ''; input.style.height = 'auto'; $('#messages').scrollTop = $('#messages').scrollHeight; }
  function sendFile(file) { if (!file) return; if (file.size > 5 * 1024 * 1024) { toast('الحد الأقصى للملف 5 ميغابايت.', 'warn'); return; } state.messages.push({ kind:'file', name:file.name || 'ملف', size:file.size, mine:true, time:Date.now() }); saveRoom(); if ($('#messages .welcome-message')) $('#messages').innerHTML = ''; renderMessage(state.messages[state.messages.length - 1]); $('#messages').scrollTop = $('#messages').scrollHeight; toast('أُضيف الملف إلى مساحتك المحلية.','ok'); }
  async function startMedia(kind) { if (!navigator.mediaDevices?.getUserMedia) { toast('المتصفح لا يدعم الوصول إلى الوسائط.', 'warn'); return; } try { state.stream = await navigator.mediaDevices.getUserMedia({ audio:true, video:kind === 'video' }); const video = $('#local-video'); video.srcObject = state.stream; $('#media-preview').classList.remove('hidden'); toast(kind === 'video' ? 'تم تشغيل معاينة الكاميرا محلياً.' : 'تم تشغيل معاينة الميكروفون محلياً.','ok'); } catch { toast('لم نتمكن من الوصول إلى الجهاز. تحقق من الإذن.','warn'); } }
  function stopMedia() { state.stream?.getTracks().forEach((track) => track.stop()); state.stream = null; const video = $('#local-video'); if (video) video.srcObject = null; $('#media-preview')?.classList.add('hidden'); }
  function toggleVoice() { if (state.recorder?.state === 'recording') { state.recorder.stop(); return; } if (!state.stream) { toast('شغّل معاينة الصوت أولاً ثم ابدأ التسجيل.','warn'); return; } try { state.chunks = []; state.recorder = new MediaRecorder(state.stream); state.recorder.ondataavailable = (event) => event.data.size && state.chunks.push(event.data); state.recorder.onstop = () => { const blob = new Blob(state.chunks, { type: state.recorder.mimeType || 'audio/webm' }); const url = URL.createObjectURL(blob); const item = document.createElement('article'); item.className = 'message mine'; item.innerHTML = `<div class="message-meta"><strong>أنت</strong><time>الآن</time></div><audio controls src="${url}"></audio>`; $('#messages').appendChild(item); toast('تم إنشاء تسجيل صوتي محلي.','ok'); }; state.recorder.start(); toast('يسجل الآن… اضغط الزر مرة أخرى للإيقاف.','ok'); } catch { toast('تعذر بدء التسجيل في هذا المتصفح.','warn'); } }
  async function copyInvite() { const url = `${location.origin}${location.pathname}?room=${state.room}`; try { await navigator.clipboard.writeText(url); toast('تم نسخ رابط المساحة.','ok'); } catch { toast(`رمز المساحة: ${state.room}`,'ok'); } }

  $('#nav-start').addEventListener('click', openModal); $('#hero-start').addEventListener('click', openModal); $('#close-modal').addEventListener('click', closeModal); $('#entry-modal').addEventListener('click', (event) => event.target === $('#entry-modal') && closeModal()); $('#create-room').addEventListener('click', () => enterRoom(false)); $('#join-room').addEventListener('click', () => enterRoom(true)); $('#join-code').addEventListener('input', (event) => { event.target.value = event.target.value.toUpperCase().replace(/[^A-Z0-9]/g, ''); }); $('#composer').addEventListener('submit', sendText); $('#message-input').addEventListener('keydown', (event) => { if (event.key === 'Enter' && !event.shiftKey) { event.preventDefault(); $('#composer').requestSubmit(); } }); $('#message-input').addEventListener('input', (event) => { event.target.style.height = 'auto'; event.target.style.height = `${Math.min(event.target.scrollHeight, 110)}px`; }); $('#attach-file').addEventListener('click', () => $('#file-input').click()); $('#file-input').addEventListener('change', (event) => { sendFile(event.target.files[0]); event.target.value = ''; }); $('#voice-note').addEventListener('click', toggleVoice); $('#audio-preview').addEventListener('click', () => startMedia('audio')); $('#video-preview').addEventListener('click', () => startMedia('video')); $('#stop-media').addEventListener('click', stopMedia); $('#share-room').addEventListener('click', copyInvite); $('#copy-code').addEventListener('click', async () => { try { await navigator.clipboard.writeText(state.room); toast('تم نسخ الرمز.','ok'); } catch { toast(state.room,'ok'); } }); $('#leave-room').addEventListener('click', showLanding); $('#room-home').addEventListener('click', showLanding); window.addEventListener('beforeunload', stopMedia);
  document.querySelectorAll('[data-mobile-action]').forEach((button) => button.addEventListener('click', () => {
    document.querySelectorAll('[data-mobile-action]').forEach((item) => item.classList.remove('active'));
    button.classList.add('active');
    const action = button.dataset.mobileAction;
    if (action === 'media') $('#media-preview').scrollIntoView({ behavior: 'smooth', block: 'center' });
    if (action === 'info') toast('هذه مساحة محلية: بياناتك لا تغادر هذا المتصفح.', 'ok');
  }));

  const queryRoom = new URLSearchParams(location.search).get('room'); if (queryRoom && queryRoom.length === 6) { $('#join-code').value = queryRoom.toUpperCase(); openModal(); }
})();
